### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by shujaatak** [igormironchik/stock#1]
I am trying to build stock on Windows and I get error while compile stock: [config.hpp] Error 127.

![error](https://user-images.githubusercontent.com/14161646/36507936-f968f70a-177c-11e8-9c59-b632eefe9296.PNG)

Compile Output:
```
C:/Qt/Qt5.10.0/Tools/mingw530_32/bin/mingw32-make -f Makefile.Release
mingw32-make[3]: Entering directory 'C:/Qt_Workspace/stock-master/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/stock/desktop'
/C/Qt_Workspace/stock-master/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/3rdparty/cfgfile/cfgfile.generator -i ../../../stock/stock/desktop/config.cfgfile -o C:/Qt_Workspace/stock-master/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/stock/desktop/config.hpp
/usr/bin/sh: /C/Qt_Workspace/stock-master/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/3rdparty/cfgfile/cfgfile.generator: No such file or directory
Makefile.Release:228: recipe for target 'config.hpp' failed
mingw32-make[3]: Leaving directory 'C:/Qt_Workspace/stock-master/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/stock/desktop'
mingw32-make[3]: *** [config.hpp] Error 127
Makefile:36: recipe for target 'release' failed
mingw32-make[2]: Leaving directory 'C:/Qt_Workspace/stock-master/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/stock/desktop'
mingw32-make[2]: *** [release] Error 2
Makefile:40: recipe for target 'sub-desktop-make_first' failed
mingw32-make[1]: Leaving directory 'C:/Qt_Workspace/stock-master/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/stock'
mingw32-make[1]: *** [sub-desktop-make_first] Error 2
Makefile:41: recipe for target 'sub-stock-make_first' failed
mingw32-make: *** [sub-stock-make_first] Error 2
03:02:12: The process "C:\Qt\Qt5.10.0\Tools\mingw530_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project stock (kit: Desktop Qt 5.10.0 MinGW 32bit)
When executing step "Make"
03:02:13: Elapsed time: 00:51.

```

**Comment by igormironchik** [comment]
This is because of problem executing executable without .exe suffix with mingw32-make. I added such suffix to project, try now. But could I ask you why are you interesting in this project? I ask because this project just started and implemented only a few features in desktop application...

**Comment by igormironchik** [comment]
Please, comment on successful build or on error, I checked with MSVC and don't want to install mingw. Thank you.

**Comment by igormironchik** [comment]
Tested with MinGW 5.3.0, fly is normal.

**Comment by shujaatak** [comment]
Still I am getting the same error, I am using QT MinGW 5.10.0, I also tried to compile with MSVC 2015 but there I get some different errors.

I can see cfgfile.generator.exe here:
C/Qt_Workspace/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/3rdparty/cfgfile/cfgfile.generator.exe

But still i get the following compile output:

```
mingw32-make[2]: Entering directory 'C:/Qt_Workspace/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/stock/desktop'
/C/Qt_Workspace/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/3rdparty/cfgfile/cfgfile.generator.exe -i ../../../stock/stock/desktop/config.cfgfile -o C:/Qt_Workspace/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/stock/desktop/config.hpp
/usr/bin/sh: /C/Qt_Workspace/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/3rdparty/cfgfile/cfgfile.generator.exe: No such file or directory
Makefile.Release:227: recipe for target 'config.hpp' failed
mingw32-make[2]: Leaving directory 'C:/Qt_Workspace/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/stock/desktop'
mingw32-make[2]: *** [config.hpp] Error 127
Makefile:36: recipe for target 'release' failed
mingw32-make[1]: Leaving directory 'C:/Qt_Workspace/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/stock/desktop'
mingw32-make[1]: *** [release] Error 2
Makefile:40: recipe for target 'sub-desktop-make_first' failed
mingw32-make: *** [sub-desktop-make_first] Error 2
14:06:59: The process "C:\Qt\Qt5.10.0\Tools\mingw530_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project stock (kit: Desktop Qt 5.10.0 MinGW 32bit)
When executing step "Make"
14:06:59: Elapsed time: 00:09.
```
In the above Compile Output, I don't know why there is linux like directory access:

**/usr/bin/sh: /C/Qt_Workspace/build-stock-Desktop_Qt_5_10_0_MinGW_32bit-Release/3rdparty/cfgfile/cfgfile.generator.exe: No such file or directory**

**Comment by shujaatak** [comment]
I am interested in stock just because of curiosity. Your readme file is very limited in information/screenshots so I'm curious what stock really does.

**Comment by shujaatak** [comment]
When compiling with Desktop Qt 5.9.1 MSVC2015 64bit, I get these errors: 

![errors](https://user-images.githubusercontent.com/14161646/36628837-df7bc562-196f-11e8-9b74-f6d43c225a60.PNG)

**Comment by igormironchik** [comment]
Can you build cfgfile with MSVC 2015?

https://github.com/igormironchik/cfgfile

Try to build this project as standalone project.

I don't have MSVC 2015 so I can't check build process with this compiler.

Can you build with MinGW under QtCreator? Don't use command line, just launch QtCreator, open stock.pro and configure project for building with MinGW. I tried with MinGW 5.3.0 and everything was fine.

And as I said already this project is under construction. I work alone on it so are possible commits that can break build process.

**Comment by shujaatak** [comment]
I can build cfgfile with MinGW under QtCreator but when i try to build stock the above mentioned error occurs.
I update you in a moment about the standalone compilation of cfgfile with MSVC 2015.

**Comment by igormironchik** [comment]
I use

$$shell_path( $$absolute_path( $${OUT_PWD}/../../3rdparty/cfgfile/cfgfile.generator$${EXE_EXT} ) )

Seems that shell_path() on your platform produces Linux style paths. Where did you get Qt from?

**Comment by shujaatak** [comment]
I get these errors while compiling cfgfile with MSVC 2015:

![errors](https://user-images.githubusercontent.com/14161646/36629348-9007c9d4-1976-11e8-9c40-4e18614b0bc5.PNG)

**Comment by shujaatak** [comment]
I have got Qt from here: http://download.qt.io/official_releases/qt/5.10/

**Comment by igormironchik** [comment]
Where did you get MinGW from? Could you install Qt and MinGW with Qt Online Installer so I can be sure that your installation is configured correct?

What about MSVC's C2899 error - this is something strange, I use "typename" keyword inside template.

**Comment by shujaatak** [comment]
I removed **$$shell_path(...)** from 
**$$shell_path( $$absolute_path( $${OUT_PWD}/../../3rdparty/cfgfile/cfgfile.generator$${EXE_EXT} ) )** 
Now stock compiles with Qt MinGW!

The above line of code now looks like this:
$$absolute_path( $${OUT_PWD}/../../3rdparty/cfgfile/cfgfile.generator$${EXE_EXT} )

But now I get this as an output:
![errors](https://user-images.githubusercontent.com/14161646/36629618-d5cd23b2-1979-11e8-85a0-346aab735537.PNG)

Can you please mention how to use stock?

By the way, I had download the MinGW version of Qt from here (It installs MinGW automatically) One can install Qt and MinGW with Qt Online Installer too!: http://download.qt.io/official_releases/qt/5.10/5.10.0/qt-opensource-windows-x86-5.10.0.exe

**Comment by shujaatak** [comment]
Regarding MSVC's C2899 error, I removed the "typename" from every line where there was that error now cfgfile compiles without any errors.

I have tried the advise [given here on stackoverflow ](https://stackoverflow.com/questions/19225458/error-c2899-typename-cannot-be-used-outside-a-template-declaration#comment28458512_19225864 )and now there are no compilation errors but just like OP, I am also wondering what the difference will be in the execution.

**Comment by igormironchik** [comment]
Don't forget " \\"... This is one line of command. Seems that you deleted it...

**Comment by igormironchik** [comment]
generate_cfg.commands = $${CFGFILE_GENERATOR} \
-i ${QMAKE_FILE_IN} -o $${OUT_PWD}/${QMAKE_FILE_BASE}.hpp

**Comment by igormironchik** [comment]
generate_cfg.commands = $${CFGFILE_GENERATOR} \\
-i ${QMAKE_FILE_IN} -o $${OUT_PWD}/${QMAKE_FILE_BASE}.hpp

**Comment by igormironchik** [comment]
-i ${QMAKE_FILE_IN} is equal to --input <file_name>

**Comment by igormironchik** [comment]
Could you check if problem exists with replacing shell_path by system_path?

**Comment by igormironchik** [comment]
template<>
struct S<int>
{
    // typename not allowed in C++98, allowed in C++11
    // accepted by g++/Clang in C++98 mode as well (not by MSVC2010)
    typedef typename V<int>::type type;    
};

As said here: typename allowed in C++11. So I guess that this is a bug of MSVC 2015.

**Comment by shujaatak** [comment]
I get the following output with shell_path replaced with system_path (fresh clean rebuild):

![errors](https://user-images.githubusercontent.com/14161646/36630204-5f279f52-1984-11e8-883a-b1b35951cbae.PNG)

**Comment by igormironchik** [comment]
I need to see your "generate_cfg.comma... " that under cmd window.

**Comment by igormironchik** [comment]
Well but I see that QtCreator generated headers...

**Comment by shujaatak** [comment]
Here it is:

![errors](https://user-images.githubusercontent.com/14161646/36630233-e975a4e2-1984-11e8-8b48-79d99a6856db.PNG)

**Comment by igormironchik** [comment]
All is ok. Does your build successful? Seems that it's so.

**Comment by shujaatak** [comment]
Yes build is successful and green!

**Comment by shujaatak** [comment]
![errors](https://user-images.githubusercontent.com/14161646/36630294-047627de-1986-11e8-892c-170b6a311aa4.PNG)

**Comment by igormironchik** [comment]
So, and what do you want?

**Comment by shujaatak** [comment]
As I mention in my [previous commnet](https://github.com/igormironchik/stock/issues/1#issuecomment-368219660) that I am in need to know how to use stock? What steps I need to follow to get the functionality you have embedded in it through your hard work?

**Comment by shujaatak** [comment]
Your Stock's Readme file can be improved through including screenshots or step by step instructions.

**Comment by shujaatak** [comment]
Pardon my ignorance - right now I'm feeling myself the dumbest, asking many questions and don't know how to use stock :(
Of course, going through the code will help but there could be many who would just like to simply read the instructions and follow them as it is.

**Comment by igormironchik** [comment]
Sure, README can be improved and will be, but as I said I just started work on this project (see commits history). To use stock just launch it from QtCreator (Ctrl+R). On first time it will ask you about some settings - IP and port of your machine on which to open sockets to communicate with mobile app, and password to protect a little communication. Press OK and app will start. Now you can add and edit products/places in the database (which is local SQLite DB).

**Comment by igormironchik** [comment]
To add product and/or place use Edit menu. And some functionality is accessible through the context menu of views.

**Comment by igormironchik** [comment]
Mobile application and desktop part can communicate on one network only, but communication is not fully implemented...

**Comment by shujaatak** [comment]
One more dumb thing (mistake) of mine: I had not selected the Desktop and I was expecting the Gui of Stock (it's for those who might make this mistake):

![errors](https://user-images.githubusercontent.com/14161646/36630515-29be1396-1989-11e8-93c0-486632cde933.PNG)

**Comment by shujaatak** [comment]
Here is the Gui of Stock - YOUR HARDWORK!
I will play with it now:

![errors](https://user-images.githubusercontent.com/14161646/36630536-ae7ab922-1989-11e8-8a97-9f20ddd8734c.PNG)

**Comment by igormironchik** [comment]
Yes, this is the same first launch of the application.

**Comment by igormironchik** [comment]
Enter your local IP, port keep as is, and enter some password. Press OK. That's all - application is configured.

**Comment by shujaatak** [comment]
It works just like you described!

By the way, would it be good if you replace shell_path by system_path in your project? I don't know if this change would have other issues.

**Comment by igormironchik** [comment]
Already.

**Comment by shujaatak** [comment]
Just for completeness, I will try to compile stock with MSVC (with typename removed) and will update you in a moment.
I hope It may help you out in some way.

**Comment by igormironchik** [comment]
MSVC 2017 just do this job, and don't think that I will support MSVC 2015. But who knows?!

**Comment by shujaatak** [comment]
I just tested it with MSVC 2015 Qt 5.9.1, It compile and runs flawlessly!
(someone who may need: Remove the "typename" keyword from every line where you get **error C2899: typename cannot be used outside a template declaration**)

![1](https://user-images.githubusercontent.com/14161646/36630688-3ef9de54-198c-11e8-968f-9b1f55e840db.PNG)

![2](https://user-images.githubusercontent.com/14161646/36630690-43565888-198c-11e8-9380-e2f543880019.PNG)

![3](https://user-images.githubusercontent.com/14161646/36630692-4719356c-198c-11e8-8584-2136db915239.PNG)

**Comment by shujaatak** [comment]
@igormironchik Thank you so much for your patience and help! You are the BEST! 🥇

**Comment by igormironchik** [comment]
FYI: I updated cfgfile, so Stock should build with MSVC 2015.
