### ISSUE TITLE
"Place" & "Description of Product" filters are case sensitive

### ISSUE THREAD

**Issue by shujaatak** [igormironchik/stock#2]
I see that the "Place" & "Description of Product" filters are case sensitive,
Is the case of "Place" & "Description of Product" filters sensitive by design?
I don't think Biscuit and biscuit are two different things.

**Comment by igormironchik** [comment]
Well, what about Code and Place so it's not so simple question to me... I'd say that case sensitive filtering is a design. But description... Possibly you are right, filtering of description should be not case sensitive. I will think about it later. I want to implement basic (Alpha) version of desktop and mobile application and show it to one man. If interest will be from his side and I will receive any feedback, so sure, I will develop this project. But at this time let me keep this issue untouched. I will keep it in mind. Thank you for your effort.

**Comment by igormironchik** [comment]
I did case insensitive filtering by description, whereas filtering by place is case sensitive yet. I wait for feedback by possible users, not sure yet, but I will close this issue. Best regards.
